Fix type inference error message
When pretty-printing function types, better add parentheses around add parentheses where needed

Before:

[info] Exception in thread "main" ilc.feature.base.TypeError: Type
error: expected (BagType(ℕ) → BagType(ℕ) → BagType(ℕ)) → (BagType(ℕ) →
BagType(ℕ)) → BagType(ℕ) → (ℕ → BagType(ℕ)) → BagType(ℕ) → BagType(ℕ)
instead of ℕ → BagType(ℕ) → BagType(ℕ) → BagType(ℕ) → BagType(ℕ) →
BagType(ℕ) → ℕ → BagType(ℕ) → BagType(ℕ) → _ in FoldGroup(BagType(ℕ), ℕ)

After:

[info] Exception in thread "main" ilc.feature.base.TypeError: Type
error: expected (BagType(ℕ) → BagType(ℕ) → BagType(ℕ)) → (BagType(ℕ) →
BagType(ℕ)) → BagType(ℕ) → (ℕ → BagType(ℕ)) → BagType(ℕ) → BagType(ℕ)
instead of (ℕ → BagType(ℕ) → BagType(ℕ)) → (BagType(ℕ) → BagType(ℕ))
→ (BagType(ℕ)) → (ℕ → BagType(ℕ)) → (BagType(ℕ)) → _ in
FoldGroup(BagType(ℕ), ℕ)

Note the extra parentheses where needed.
Of course, now there are too many parentheses, but I can cope with that,
while I can't cope with missing parentheses.

Old-commit-hash: 40a841394efab6e2b6ddf0c425626713e65efd51