Fix Scalac crash while compiling Build.scala
This type annotation fixes a crash caused by previous commit, which
prevents from loading the project. The error message starts with:

java.lang.Error: A in trait Seq cannot be instantiated from sbt.Types.Id[Seq[sbt.Task[Seq[java.io.File]]]] with sbt.Types.Id[Seq[sbt.TestFramework]]
	at scala.tools.nsc.symtab.SymbolTable.abort(SymbolTable.scala:34)
	at
	scala.tools.nsc.symtab.Types$AsSeenFromMap.throwError$1(Types.scala:3494)
[...]

SBT 0.13 would also avoid the error.

Old-commit-hash: 2fb54ed14f766af84f993fb1151f38f66a4d4c2a