Fix NotSerializableException in previous commit
The previous error was reproducible as:
$ sbt
> test-only ilc.examples.bench.MapSuccBagsBenchmark
[error] Could not run test ilc.examples.bench.MapSuccBagsBenchmark:
java.io.NotSerializableException: ilc.language.bacchus.Libraries$

Fix that by adding 'extends Serializable' to Libraries. That class is
used (somehow) through closures from that class; I suppose the code is
trying to serialize the singleton instance of that class since the
closures refer to it.

Old-commit-hash: 0d735d4f18f7e667521c1fc33fc2f535483266ae